import { defineField, defineArrayMember, defineType } from 'sanity'

export const project = defineType({
  name: 'project',
  title: 'Proyecto',
  type: 'document',
  groups: [
    { name: 'general', title: 'General' },
    { name: 'detalle', title: 'Página de detalle' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Nombre del cliente/proyecto',
      type: 'string',
      group: 'general',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Dirección web (slug)',
      description: 'Se genera solo a partir del nombre. Define la URL: /proyecto/lo-que-escribas-aqui',
      type: 'slug',
      group: 'general',
      options: { source: 'title', maxLength: 60 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Categoría',
      description: 'Se usa para los filtros de la página de Portafolio.',
      type: 'string',
      group: 'general',
      options: { list: ['Tiendas', 'Especializado', 'Informativo'], layout: 'radio' },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'service',
      title: 'Servicio',
      description: 'Ejemplo: Diseño Web para Clínica Estética',
      type: 'string',
      group: 'general',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'image',
      title: 'Foto de portada',
      description: 'Se usa en la tarjeta del carrusel de Inicio y en la grilla de Portafolio.',
      type: 'image',
      group: 'general',
      options: { hotspot: true },
      fields: [defineField({ name: 'alt', title: 'Texto alternativo', type: 'string' })],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'shortDescription',
      title: 'Descripción corta',
      description: 'Se muestra en la tarjeta del carrusel de Inicio (hasta 3 líneas).',
      type: 'text',
      rows: 2,
      group: 'general',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'featuredOnHome',
      title: '¿Mostrar en el carrusel de Inicio?',
      type: 'boolean',
      group: 'general',
      initialValue: false,
    }),
    defineField({
      name: 'order',
      title: 'Orden',
      description: 'Los números más bajos aparecen primero en Portafolio y en el carrusel de Inicio.',
      type: 'number',
      group: 'general',
      initialValue: 0,
    }),
    defineField({
      name: 'caseImage',
      title: 'Foto grande de la página de detalle',
      type: 'image',
      group: 'detalle',
      options: { hotspot: true },
      fields: [defineField({ name: 'alt', title: 'Texto alternativo', type: 'string' })],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'objective',
      title: 'Objetivo',
      description: 'Una frase: qué se buscaba lograr con este proyecto.',
      type: 'text',
      rows: 2,
      group: 'detalle',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'story',
      title: 'Historia del proyecto',
      description: 'Uno o más párrafos. Arrastra para reordenar.',
      type: 'array',
      group: 'detalle',
      of: [defineArrayMember({ type: 'text', rows: 3 })],
      validation: (Rule) => Rule.min(1).error('Hace falta al menos un párrafo.'),
    }),
    defineField({
      name: 'benefits',
      title: 'Beneficios del proyecto',
      type: 'array',
      group: 'detalle',
      of: [
        defineArrayMember({
          type: 'object',
          name: 'benefit',
          fields: [
            defineField({ name: 'title', title: 'Título', type: 'string', validation: (Rule) => Rule.required() }),
            defineField({ name: 'text', title: 'Texto', type: 'text', rows: 2, validation: (Rule) => Rule.required() }),
          ],
          preview: { select: { title: 'title', subtitle: 'text' } },
        }),
      ],
    }),
    defineField({
      name: 'closingQuestion',
      title: 'Pregunta de cierre',
      description: 'La pregunta grande antes del botón final de contacto.',
      type: 'string',
      group: 'detalle',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'closingSubtext',
      title: 'Texto bajo la pregunta de cierre',
      type: 'string',
      group: 'detalle',
      validation: (Rule) => Rule.required(),
    }),
  ],
  orderings: [
    {
      title: 'Orden manual',
      name: 'orderAsc',
      by: [{ field: 'order', direction: 'asc' }],
    },
  ],
  preview: {
    select: { title: 'title', subtitle: 'service', media: 'image' },
  },
})
