import { defineField, defineType } from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Ajustes generales',
  type: 'document',
  groups: [
    { name: 'marca', title: 'Marca y contacto' },
    { name: 'chat', title: 'Asistente de chat' },
    { name: 'comportamiento', title: 'Comportamiento' },
  ],
  fields: [
    defineField({
      name: 'brandName',
      title: 'Nombre de la marca',
      description: 'Se usa como texto alternativo del logo y en el copyright del pie de página.',
      type: 'string',
      group: 'marca',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'logo',
      title: 'Logo',
      description: 'Se muestra en la cabecera, el menú y la sección de contacto de cada página.',
      type: 'image',
      group: 'marca',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'phoneDisplay',
      title: 'Teléfono (como se muestra)',
      description: 'Escríbelo tal cual quieres que se vea, por ejemplo: +593 96 260 6760',
      type: 'string',
      group: 'marca',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'email',
      title: 'Correo de contacto',
      type: 'string',
      group: 'marca',
      validation: (Rule) => Rule.required().email(),
    }),
    defineField({
      name: 'addressLine',
      title: 'Ciudad / dirección',
      description: 'Texto corto, por ejemplo: Quito - Ecuador',
      type: 'string',
      group: 'marca',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'mapLink',
      title: 'Enlace a Google Maps',
      description: 'A dónde lleva el botón "Ver en el Mapa".',
      type: 'url',
      group: 'marca',
      validation: (Rule) => Rule.required().uri({ scheme: ['http', 'https'] }),
    }),
    defineField({
      name: 'whatsappNumber',
      title: 'Número de WhatsApp (solo dígitos, con código de país)',
      description: 'A este número se envían los formularios de "Cotizar proyecto", por ejemplo: 593998381419',
      type: 'string',
      group: 'marca',
      validation: (Rule) =>
        Rule.required().regex(/^\d+$/, { name: 'solo números' }).error('Escribe solo números, sin espacios ni símbolos.'),
    }),
    defineField({
      name: 'whatsappShortLink',
      title: 'Enlace directo de WhatsApp',
      description: 'Se usa en el botón flotante, el menú y el asistente de chat. Puede ser un enlace corto (w.app/...) o wa.me.',
      type: 'url',
      group: 'marca',
      validation: (Rule) => Rule.required().uri({ scheme: ['http', 'https'] }),
    }),
    defineField({
      name: 'footerCopyright',
      title: 'Texto del pie de página',
      description: 'Se muestra centrado debajo de los enlaces, en todas las páginas.',
      type: 'string',
      group: 'marca',
      initialValue: 'Todos los derechos reservados.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'chatEnabled',
      title: '¿Mostrar el asistente de chat?',
      description: 'Si lo apagas, el botón flotante de la portada solo abre WhatsApp — sin el bot ni sus opciones.',
      type: 'boolean',
      group: 'chat',
      initialValue: true,
    }),
    defineField({
      name: 'chatWebhookUrl',
      title: 'Webhook del asistente (n8n)',
      description: 'A dónde se envían los mensajes que escribe el visitante. Solo lo cambia quien administra el flujo de automatización.',
      type: 'url',
      group: 'chat',
      hidden: ({ document }) => !document?.chatEnabled,
    }),
    defineField({
      name: 'chatBotAvatar',
      title: 'Foto del asistente',
      type: 'image',
      group: 'chat',
      hidden: ({ document }) => !document?.chatEnabled,
    }),
    defineField({
      name: 'chatQuickReplies',
      title: 'Respuestas rápidas',
      description: 'Los botones que ve el visitante antes de escribir. La "Pregunta" es lo que realmente se envía al asistente.',
      type: 'array',
      group: 'chat',
      hidden: ({ document }) => !document?.chatEnabled,
      of: [
        {
          type: 'object',
          name: 'quickReply',
          fields: [
            defineField({ name: 'label', title: 'Texto del botón', type: 'string', validation: (Rule) => Rule.required() }),
            defineField({ name: 'question', title: 'Pregunta que envía', type: 'string', validation: (Rule) => Rule.required() }),
          ],
          preview: { select: { title: 'label', subtitle: 'question' } },
        },
      ],
    }),
    defineField({
      name: 'carouselAutoplay',
      title: '¿Avanzar solo el carrusel de proyectos de portada?',
      type: 'boolean',
      group: 'comportamiento',
      initialValue: true,
    }),
    defineField({
      name: 'showConsultBadge',
      title: '¿Mostrar el aviso de "personas consultando ahora"?',
      type: 'boolean',
      group: 'comportamiento',
      initialValue: true,
    }),
    defineField({
      name: 'showDangerTape',
      title: '¿Mostrar la cinta de "PELIGRO" animada?',
      description: 'La franja amarilla y negra que aparece al bajar por la sección de problemas, en la portada.',
      type: 'boolean',
      group: 'comportamiento',
      initialValue: true,
    }),
  ],
  preview: {
    prepare: () => ({ title: 'Ajustes generales' }),
  },
})
